/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandProtectionRouteImport } from './routes/brand-protection'
import { Route as BrandStrategyRouteImport } from './routes/brand-strategy'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CollaborationRouteImport } from './routes/collaboration'
import { Route as CollobrationRouteImport } from './routes/collobration'
import { Route as CommerceMarketplacesRouteImport } from './routes/commerce-marketplaces'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DistributionOmnichannelRouteImport } from './routes/distribution-omnichannel'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InternationalExpansionRouteImport } from './routes/international-expansion'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PerformanceCreativeRouteImport } from './routes/performance-creative'
import { Route as ResearchIntelligenceRouteImport } from './routes/research-intelligence'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TheWorkRouteImport } from './routes/the-work'
import { Route as WorkRouteImport } from './routes/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandProtectionRoute = BrandProtectionRouteImport.update({
  id: '/brand-protection',
  path: '/brand-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandStrategyRoute = BrandStrategyRouteImport.update({
  id: '/brand-strategy',
  path: '/brand-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationRoute = CollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const CollobrationRoute = CollobrationRouteImport.update({
  id: '/collobration',
  path: '/collobration',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceMarketplacesRoute = CommerceMarketplacesRouteImport.update({
  id: '/commerce-marketplaces',
  path: '/commerce-marketplaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionOmnichannelRoute = DistributionOmnichannelRouteImport.update({
  id: '/distribution-omnichannel',
  path: '/distribution-omnichannel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalExpansionRoute = InternationalExpansionRouteImport.update({
  id: '/international-expansion',
  path: '/international-expansion',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceCreativeRoute = PerformanceCreativeRouteImport.update({
  id: '/performance-creative',
  path: '/performance-creative',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIntelligenceRoute = ResearchIntelligenceRouteImport.update({
  id: '/research-intelligence',
  path: '/research-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TheWorkRoute = TheWorkRouteImport.update({
  id: '/the-work',
  path: '/the-work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-protection': typeof BrandProtectionRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/capabilities': typeof CapabilitiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/collaboration': typeof CollaborationRoute
  '/collobration': typeof CollobrationRoute
  '/commerce-marketplaces': typeof CommerceMarketplacesRoute
  '/contact': typeof ContactRoute
  '/distribution-omnichannel': typeof DistributionOmnichannelRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/international-expansion': typeof InternationalExpansionRoute
  '/partners': typeof PartnersRoute
  '/performance-creative': typeof PerformanceCreativeRoute
  '/research-intelligence': typeof ResearchIntelligenceRoute
  '/services': typeof ServicesRoute
  '/the-work': typeof TheWorkRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-protection': typeof BrandProtectionRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/capabilities': typeof CapabilitiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/collaboration': typeof CollaborationRoute
  '/collobration': typeof CollobrationRoute
  '/commerce-marketplaces': typeof CommerceMarketplacesRoute
  '/contact': typeof ContactRoute
  '/distribution-omnichannel': typeof DistributionOmnichannelRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/international-expansion': typeof InternationalExpansionRoute
  '/partners': typeof PartnersRoute
  '/performance-creative': typeof PerformanceCreativeRoute
  '/research-intelligence': typeof ResearchIntelligenceRoute
  '/services': typeof ServicesRoute
  '/the-work': typeof TheWorkRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-protection': typeof BrandProtectionRoute
  '/brand-strategy': typeof BrandStrategyRoute
  '/capabilities': typeof CapabilitiesRoute
  '/case-studies': typeof CaseStudiesRoute
  '/collaboration': typeof CollaborationRoute
  '/collobration': typeof CollobrationRoute
  '/commerce-marketplaces': typeof CommerceMarketplacesRoute
  '/contact': typeof ContactRoute
  '/distribution-omnichannel': typeof DistributionOmnichannelRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/international-expansion': typeof InternationalExpansionRoute
  '/partners': typeof PartnersRoute
  '/performance-creative': typeof PerformanceCreativeRoute
  '/research-intelligence': typeof ResearchIntelligenceRoute
  '/services': typeof ServicesRoute
  '/the-work': typeof TheWorkRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand-protection'
    | '/brand-strategy'
    | '/capabilities'
    | '/case-studies'
    | '/collaboration'
    | '/collobration'
    | '/commerce-marketplaces'
    | '/contact'
    | '/distribution-omnichannel'
    | '/industries'
    | '/insights'
    | '/international-expansion'
    | '/partners'
    | '/performance-creative'
    | '/research-intelligence'
    | '/services'
    | '/the-work'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand-protection'
    | '/brand-strategy'
    | '/capabilities'
    | '/case-studies'
    | '/collaboration'
    | '/collobration'
    | '/commerce-marketplaces'
    | '/contact'
    | '/distribution-omnichannel'
    | '/industries'
    | '/insights'
    | '/international-expansion'
    | '/partners'
    | '/performance-creative'
    | '/research-intelligence'
    | '/services'
    | '/the-work'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brand-protection'
    | '/brand-strategy'
    | '/capabilities'
    | '/case-studies'
    | '/collaboration'
    | '/collobration'
    | '/commerce-marketplaces'
    | '/contact'
    | '/distribution-omnichannel'
    | '/industries'
    | '/insights'
    | '/international-expansion'
    | '/partners'
    | '/performance-creative'
    | '/research-intelligence'
    | '/services'
    | '/the-work'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandProtectionRoute: typeof BrandProtectionRoute
  BrandStrategyRoute: typeof BrandStrategyRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CollaborationRoute: typeof CollaborationRoute
  CollobrationRoute: typeof CollobrationRoute
  CommerceMarketplacesRoute: typeof CommerceMarketplacesRoute
  ContactRoute: typeof ContactRoute
  DistributionOmnichannelRoute: typeof DistributionOmnichannelRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRoute
  InternationalExpansionRoute: typeof InternationalExpansionRoute
  PartnersRoute: typeof PartnersRoute
  PerformanceCreativeRoute: typeof PerformanceCreativeRoute
  ResearchIntelligenceRoute: typeof ResearchIntelligenceRoute
  ServicesRoute: typeof ServicesRoute
  TheWorkRoute: typeof TheWorkRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-protection': {
      id: '/brand-protection'
      path: '/brand-protection'
      fullPath: '/brand-protection'
      preLoaderRoute: typeof BrandProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-strategy': {
      id: '/brand-strategy'
      path: '/brand-strategy'
      fullPath: '/brand-strategy'
      preLoaderRoute: typeof BrandStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration': {
      id: '/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof CollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collobration': {
      id: '/collobration'
      path: '/collobration'
      fullPath: '/collobration'
      preLoaderRoute: typeof CollobrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce-marketplaces': {
      id: '/commerce-marketplaces'
      path: '/commerce-marketplaces'
      fullPath: '/commerce-marketplaces'
      preLoaderRoute: typeof CommerceMarketplacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution-omnichannel': {
      id: '/distribution-omnichannel'
      path: '/distribution-omnichannel'
      fullPath: '/distribution-omnichannel'
      preLoaderRoute: typeof DistributionOmnichannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-expansion': {
      id: '/international-expansion'
      path: '/international-expansion'
      fullPath: '/international-expansion'
      preLoaderRoute: typeof InternationalExpansionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-creative': {
      id: '/performance-creative'
      path: '/performance-creative'
      fullPath: '/performance-creative'
      preLoaderRoute: typeof PerformanceCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-intelligence': {
      id: '/research-intelligence'
      path: '/research-intelligence'
      fullPath: '/research-intelligence'
      preLoaderRoute: typeof ResearchIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-work': {
      id: '/the-work'
      path: '/the-work'
      fullPath: '/the-work'
      preLoaderRoute: typeof TheWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandProtectionRoute: BrandProtectionRoute,
  BrandStrategyRoute: BrandStrategyRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CollaborationRoute: CollaborationRoute,
  CollobrationRoute: CollobrationRoute,
  CommerceMarketplacesRoute: CommerceMarketplacesRoute,
  ContactRoute: ContactRoute,
  DistributionOmnichannelRoute: DistributionOmnichannelRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRoute,
  InternationalExpansionRoute: InternationalExpansionRoute,
  PartnersRoute: PartnersRoute,
  PerformanceCreativeRoute: PerformanceCreativeRoute,
  ResearchIntelligenceRoute: ResearchIntelligenceRoute,
  ServicesRoute: ServicesRoute,
  TheWorkRoute: TheWorkRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
